version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql:8.0.34
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_USER: ${MYSQL_INSTALLER_USERID}
      MYSQL_PASSWORD: ${MYSQL_INSTALLER_PWD}
#      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "${MYSQL_TCP_PORT}:3306"
#      - "50001:3306"
    volumes:
      - ./tests/scripts:/docker-entrypoint-initdb.d/:ro
