version: '3'

services:
  sqldbwrpr_test:
    image: mysql:8.0.21
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: NotSecurePassword
      MYSQL_DATABASE: sqldbwrpr
    ports:
      - "3308:3306"
