# docker-compose.yaml
services:
  db:
    image: postgres:16-alpine
    environment:
      INSTALLER_USER_ID: "${INSTALLER_USERID}"
      INSTALLER_USER_PWD: "${INSTALLER_PWD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PROJECT_NAME: "${PROJECT_NAME}"
    ports:
      - "${MYSQL_TCP_PORT}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD -h 127.0.0.1 --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
