DROP DATABASE IF EXISTS ToDelete;
CREATE DATABASE IF NOT EXISTS sqldbwrpr_db;
CREATE USER IF NOT EXISTS 'installer'@'%' IDENTIFIED BY 'N0Pa55wrd';
GRANT ALL PRIVILEGES ON *.* TO 'installer'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
